### PR TITLE
New bathymetry

### PR DESCRIPTION
**Pull request by AchrefAO**
New bathymetry for TP2

### CODE REVIEW

**Review by lilleannette — CHANGES_REQUESTED** [review]
@AchrefAO I think you should only update the topography version "03", not "02".
Unless you have a specific reason to change version "02".

**Comment by AchrefAO** [comment]
> @AchrefAO I think you should only update the topography version "03", not "02".
> Unless you have a specific reason to change version "02".

Absolutely, I have added the version 3 and replaced the files regional.depth.ab and regional.grid.ab

**Comment by lilleannette** [comment]
> > @AchrefAO I think you should only update the topography version "03", not "02".
> > Unless you have a specific reason to change version "02".
> 
> Absolutely, I have added the version 3 and replaced the files regional.depth.ab and regional.grid.ab

But I still see the vesion 02 topography changed under "Files changed" on the pull request.

**Comment by AchrefAO** [comment]
> > > @AchrefAO I think you should only update the topography version "03", not "02".
> > > Unless you have a specific reason to change version "02".
> > 
> > 
> > Absolutely, I have added the version 3 and replaced the files regional.depth.ab and regional.grid.ab
> 
> But I still see the vesion 02 topography changed under "Files changed" on the pull request.

@lilleannette  Can you refuse it and I'll submit again

**Pull request closed without merging**
