### PR TITLE
Issue ec operational

### PR DESCRIPTION
**Pull request by AlfaAli**

### CODE REVIEW

**Review by Jipingnersc — COMMENTED** [review]
About the minimal limit, have you found this issue in the operational forcing? 

What do you think to add this limit to other accumulated variable like precipitation?

**Comment by AlfaAli** [comment]
> About the minimal limit, have you found this issue in the operational forcing?
yes this limit needed for the operational forcing because sometimes there are negative values that introduced by upstream interpolation/de-accumulation. Both SSRD&STRD must be positive.
This may not be needed for ERA5, but it does not harm applying this limit. 
> 
> What do you think to add this limit to other accumulated variable like precipitation?
I don't think this is important for precipitation.

**Review by Jipingnersc — COMMENTED** [review]
For the added functions in hycom_atmfor.py, the concerned test is hard due to there are no sampling forcing files. 

Could you share some forcing files for test on Betzy or Fram?

**Comment by AlfaAli** [comment]
@Jipingnersc 
You can find ec_op forcing files on frame under NS2993K, under the shared folder METNO_2_NERSC/ECMWF_OP 
Then try something like:
bin/atmo_synoptic.sh ec_op+ssrd+strd 2022-01-01T00:00:00 2022-01-10T00:00:00 
The option  "ec_op+ssrd+strd" means both ssrd and strd are coming from ECMWF

**Review by Jipingnersc — APPROVED** [review]

**Pull request merged**
