### PR TITLE
allow for restart from ice_initial.nc, fields aice and hi

### PR DESCRIPTION
**Pull request by TillRasmussen**
Expand the options for cold start from a file named ice_initial with fields aice and hi.
in namelist ice_in ice_ic must be set to 'read' and ocn_data_dir should be the path of the location of the file. If in SCRATCH './' is sufficient. All ice is put in the same category.

### CODE REVIEW

**Comment by TillRasmussen** [comment]
@Jipingnersc I double checked the stability and added an extra requirement (aice>0.15). Ideally this would be based on sst, however this has not been read into CICE. CICE may become unstable if ice is added when sst in the first time step is above the freezing point.
@AlfaAli I changed the name of the namelist

**Review by Jipingnersc — CHANGES_REQUESTED** [review]
Based on my test using one TP5 model run, I faced some potential issues as follows:
1) ice_ic also is useful in another python script: NERSC-HYCOM-CICE/bin/cice_limits.py
 if init :
      nml["setup_nml"]["runtype"]="initial"
      nml["setup_nml"]["restart"]=False
      nml["setup_nml"]["use_restart_time"]=False
      #nml["setup_nml"]["ice_ic"]="default"
      nml["setup_nml"]["ice_ic"]="read"       
The last sentence should be added in this routine when using the definition ice_ic in ice_in

2) The default directory of "ocn_data_dir" in ice_in was not used before. But when reading ice_initial.nc, the model will read the file under that directory. So I tried to define ocn_data_dir="./" and copy the file ice_initial.nc to the directory of SCRATCH.

3) Using the reanalysis of TP4b in 1991-2020, the mean of sea ice state has been interpolated on TP5 grids. Then the model was tested, but broken due to this kind of error:
picard convergence failed!   (ice_mushy_thermo)
ice_therm_mushy solver failure

Afterwards, more measurements for the input sea ice concentration and thickness are considered in ice_init.F90:
fieldname = 'aice'
         call ice_read_nc &
             (fid, 1, fieldname, abar2d(:,:,:), .true., &
             field_loc_center, field_type_scalar)
             where(abar2d<0.15) abar2d=0.0
             fieldname = 'hi'
         call ice_read_nc &
             (fid, 1, fieldname, hbar2d(:,:,:), .true., &
             field_loc_center, field_type_scalar)
             where(abar2d<0.15) hbar2d=0.0
          call ice_close_nc(fid)

In the end, the model was successful to use the new ice cover through ice_initial.nc.

**Comment by TillRasmussen** [comment]
@Jipingnersc thank you for the review.
1/ The default version still works (adds ice north of a given latitude if sst is cold enough).  The input is currently a true/false. It could be changed to init={latitude,user,continue}.
2/ Yes correct. 
3/ This method is sensitive to too warm temperatures. In the default it puts ice north and south of a given latitude on the northern and southern hemisphere if sst is cold enough compared to the freezing point. The NERSC-HYCOM-CICE system do not know anything about the sst or the sss. These are not initialized until the first coupling, which is after initialization. A solution could be to include read in of sss and sst to the method and reduce the icecover based on these. This requires the same fields as HYCOM in started from otherwize there will still be issues.

**Comment by Jipingnersc** [comment]
Hi Til, 
The additional push looks refusing by permission.

[xiejp@login-2.BETZY ~/Developing/NERSC-HYCOM-CICE]$ git push --set-upstream origin remotes/origin/newiceinit
Username for 'https://github.com': jipingnersc
Password for 'https://jipingnersc@github.com': 
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/TillRasmussen/NERSC-HYCOM-CICE.git
 ! [remote rejected] origin/newiceinit -> origin/newiceinit (permission denied)
error: failed to push some refs to 'https://github.com/TillRasmussen/NERSC-HYCOM-CICE.git'

**Comment by TillRasmussen** [comment]
I am not sure that you are allowed to directly push to my branch. Maybe you need to make a clone of my branch and make a pull request

**Comment by TillRasmussen** [comment]
Added ability to read in sst and sss. This requires that these fields are available in ice_initial.nc (just like aice and hi). If the fields are coordinated ice will not be placed where water is too warm.
The following must be set
    sss_data_type = 'hycom'
    sst_data_type = 'hycom'
If ice_initial.nc is located in SCRATCH then 
ocn_data_dir="./"

**Comment by Jipingnersc** [comment]
Great, it sounds very helpful. 
Only one small comment for the parameter setting of "sss_data_type = 'hycom'
sst_data_type = 'hycom'", where is it to keep this explanation, or in some docuement?

**Review by Jipingnersc — APPROVED** [review]

**Comment by TillRasmussen** [comment]
> 

I did have the same question. It would be nice to have a doc page for the NERSC setup e.g readthedocs.
This could describe how to setup a new domain, what do the cpp flags do,  which differences are there compared to the original system. Maybe this should be raised at a meeting?

**Pull request merged**
