### PR TITLE
Hycom twoversions

### PR DESCRIPTION
**Pull request by Jipingnersc**
Add Hycom2.3 as one option for the ocean model in Hycom_cice. The script of compile_model.sh has been updated to adapt with two accessible versions of 2.2.98 and 2.3. The sea ice model remains the same as before.

In hycom2.3, the new compile flags "-DNERSC_saltflux -DNERSC_T2F" needs to be tested afterwards.

### CODE REVIEW

**Comment by TillRasmussen** [comment]
@Jipingnersc Is it necessary to have all the files in the OASIS library?

**Comment by Jipingnersc** [comment]
> @Jipingnersc Is it necessary to have all the files in the OASIS library?

Actually, I am not sure who will use this part so I keep it as before. Could you delete some redundant files if possible?

**Comment by TillRasmussen** [comment]
@Jipingne

> > @Jipingnersc Is it necessary to have all the files in the OASIS library?
> 
> Actually, I am not sure who will use this part so I keep it as before. Could you delete some redundant files if possible?

Ok

**Comment by lilleannette** [comment]
> @Jipingnersc Is it necessary to have all the files in the OASIS library?

The four files in the folder called Oasis are used to run hycom only and hycom coupe to nextsim, so please leave untouched.

**Comment by TillRasmussen** [comment]
Is nextsim compiled with cpp flag USE_ESMF4 ?
if not then hycom.F90 and Oasis/hycom.F are the same except for the change to Fortran 90. I would suggest to merge these two files. Alternatively name the one in the Oasis directory to something like hycom_nextsim.F or something like that. 

Another thing stmt functions are in this version merged to one file. The choice of statement function is now handled by CPP flags (-DEOS_SIG0, DEOS_7T), where the first is the reference density and the latter is the number of terms in the equation. This means that the ALT_CODE could also be moved.

-DNERSC_T2F handles the energy exchange with CICE. If this is not set it then it assumes a constant T and S in the mixlayer defined either by a maximum exchange depth set in the blkdat file or the mixlayer. If this is set it uses the energy exchange that was implemented in previous versions at NERSC. This calculates the energy for each layer.

-DNERSC_saltflux switches the salt flux from ice to ocean. This is either the traditonal HYCOM exchange or one implemented by the Canadians in NEMO-CICE.

**Comment by lilleannette** [comment]
The OASIS version is not compiled without USE_ESMF4 flag, so the two can be merged then, but please make sure Heather tests that this new HYCOM-Nextsim version can compile and run before approving the pull request.

I don’t know the details of the other parts, so I leave that to Jiping.

Annette

Annette Samuelsen
forskningsleder | Research Leader

***@***.*** | +47 932 38 202


Stiftelsen Nansen Senter for Miljø og Fjernmåling
Nansen Environmental and Remote Sensing Center
Jahnebakken 3 | N-5007 Bergen | Norway
***@***.*** | nersc.no<https://nersc.no> | +47 55 20 58 00

[cid:logo_de1c6baf-5da6-4f53-b1e5-34827df1144c.jpg]


Konfidensialitet. Informasjonen i denne e-posten er utelukkende ment for bruk av adressaten(e),
og kan inneholde konfidensiell informasjon som ikke kan deles uten avsenders skriftlige samtykke.

Notice of confidentiality. The information contained in this e-mail is intended solely for the use of
the addressee(s) and may contain confidential or legally privileged information.
From: TRasmussen ***@***.***>
Date: Friday, 16 August 2024 at 13:11
To: nansencenter/NERSC-HYCOM-CICE ***@***.***>
Cc: Annette Samuelsen ***@***.***>, Review requested ***@***.***>
Subject: Re: [nansencenter/NERSC-HYCOM-CICE] Hycom twoversions (PR #258)

Is nextsim compiled with cpp flag USE_ESMF4 ?
if not then hycom.F90 and Oasis/hycom.F are the same except for the change to Fortran 90. I would suggest to merge these two files. Alternatively name the one in the Oasis directory to something like hycom_nextsim.F or something like that.

Another thing stmt functions are in this version merged to one file. The choice of statement function is now handled by CPP flags (-DEOS_SIG0, DEOS_7T), where the first is the reference density and the latter is the number of terms in the equation. This means that the ALT_CODE could also be moved.

-DNERSC_T2F handles the energy exchange with CICE. If this is not set it then it assumes a constant T and S in the mixlayer defined either by a maximum exchange depth set in the blkdat file or the mixlayer. If this is set it uses the energy exchange that was implemented in previous versions at NERSC. This calculates the energy for each layer.

-DNERSC_saltflux switches the salt flux from ice to ocean. This is either the traditonal HYCOM exchange or one implemented by the Canadians in NEMO-CICE.

**Review by caglartac — APPROVED** [review]

**Pull request merged**
