### PR TITLE
Issue85 mscprogs compile fail

### PR DESCRIPTION
**Pull request by HarryLuyt**
I have added the subdirectories outlines in issue #85 in order to ensure MSCPROGS compiles without failure.
These subdirectories are in the main branch, but must've got lost somewhere along the way in develop.

### CODE REVIEW

**Comment by Jipingnersc** [comment]
Right, these temporary directories are needed by compiling.

**Comment by HarryLuyt** [comment]
> Right, these temporary directories are needed by compiling.

Indeed. I think the best approach is to write the makefiles in such a way that these temporary, but necessary, folders are created if they aren't there. But I'm no expert in this and wouldn't know if there are any reasons not to do so.

**Comment by Jipingnersc** [comment]
> > Right, these temporary directories are needed by compiling.
> 
> Indeed. I think the best approach is to write the makefiles in such a way that these temporary, but necessary, folders are created if they aren't there. But I'm no expert in this and wouldn't know if there are any reasons not to do so.

A: Before these directories are not included in GitHub, so the attempt to add them was fail. I can check your updated branch this time.

**Comment by Jipingnersc** [comment]
The compiling using this branch is successfully completed on Fram.

**Review by Jipingnersc — APPROVED** [review]

**Pull request merged**
