### PR TITLE
Hycomv2 3 First source code push

### PR DESCRIPTION
**Pull request by TillRasmussen**
In order to make sure that the right things get in I will push the new version in chunks. First is the source code.

### CODE REVIEW

**Review by Jipingnersc — CHANGES_REQUESTED** [review]
I tried to complete the compiling of hycom_cice, and found the same file for compile_model.sh under the directory of NERSC-HYCOM-CICE/bin. It does not support the compiling of hycom2.3.

if [ "${V}" == "2.2.98" ]; then
	sourcedir=$NHCROOT/hycom/RELO/src_${V}ZA-07Tsig0-i-sm-sse_relo_mpi/
elif [ "${V}" == "2.2.98.01" ]; then
        sourcedir=$NHCROOT/hycom/RELO/src_${V}ZA-07Tsig0-i-sm-sse_relo_mpi/
else
	sourcedir=$NHCROOT/hycom/RELO/src_${V}G-17Tsig2-SD-i_relo_mpi/ 
	sourcedir=$NHCROOT/hycom/RELO/HYCOM_NERSC_src_v2.3/ 
fi

So I think this branch could miss the relevant script to do this job.

**Comment by TillRasmussen** [comment]
@Jipingnersc Thank you.  I will update it

**Comment by TillRasmussen** [comment]
@Jipingnersc I have updated some issues here and there. It is running a longer test now, thus it compiles and run.
The issue that you found was that I moved the name of the folder from 3.1 to 2.3 and forgot to change it in the script.

Note that I changed a few values back from yours (if I remember correct). I think that we should make them variables and add them to the name list if they are to be tuned. The parameters are
ice_ruf in ice_constant.F90
cos(w) and sin(w) in ice_dyn_shared.F90
Pstar in ice_mechred.F90

The values that you added are currently commented out.

**Comment by Jipingnersc** [comment]
> @Jipingnersc I have updated some issues here and there. It is running a longer test now, thus it compiles and run. The issue that you found was that I moved the name of the folder from 3.1 to 2.3 and forgot to change it in the script.
> 

Thanks Till for your response. I will try it again and feedback to you later.

**Comment by Jipingnersc** [comment]
Hi Till,
I am trying to run a short model run after model compiling. 
Could you share blkdat.input used in that case?

**Comment by Jipingnersc** [comment]
Under the current env on Betzy, the modules are upgraded with

# updated in March 2024
ml purge
ml load CMake/3.23.1-GCCcore-11.3.0
ml load ESMF/8.3.0-iomkl-2022a
ml load FFTW/3.3.10-GCC-11.3.0
ml load UDUNITS/2.2.28-GCCcore-11.3.0
ml load Python/3.10.4-GCCcore-11.3.0
ml load GSL/2.7-intel-compilers-2022.1.0

It works for HYCOM 2.2.98, so I delete the module loading in bin/compile_model.sh
#     ml purge
#     module load Python/3.8.2-GCCcore-9.3.0
#     module load intel/2021a
#     module load ESMF/8.0.1-intel-2020a
#     module load FFTW/3.3.8-intel-2020a
#     module load UDUNITS/2.2.26-GCCcore-9.3.0
#     module load CMake/3.16.4-GCCcore-9.3.0

Another a small change is in /hycom/RELO/config/Linux.betzy.ifort_cice
EXTRALIBS     = -L${ESMF_LIB_DIR}/ -lesmf_fullylinked -lfftw3 -lmkl -lnetcdff -lnetcdf -lstdc++

And then the hycom_cice can be compiled, but a short model run has not been tested yet.

**Comment by TillRasmussen** [comment]
@Jipingnersc I have added a new experiment folder exp_02.3. The files needed should be in there

**Comment by TillRasmussen** [comment]
forcing.surtmp.a I dont have one. It is only read if one of the following flags are set:
surtmp: Did you set lwflag = 2 or sstlfg = 2 or icmflg = 2  ticegr=0.0?
I dont need it.

This is the standard restart naming. It should be fairly easy to change. Someone at NERSC has probably at some point found it annoying that one have to link the restart_out to restart_in

**Comment by Jipingnersc** [comment]
Thank Til. The new run with hycom2.3 has been done on Betzy, the related result will be compared with the current version. 
Now the main differences are highlighted on the salinity near sea surface. So based on the initial checking into the code, I found one bug in thermf.F90 of  hycom2.3 at Line 1939 as follows:
        if     (abs(sssdif).gt.abs(sssrmx(i,j))) then  !  large sss anomaly
           if     (sssrmx(i,j).lt.0.0) then
                sssdif = 0.0    !  turn off relaxation except under ice
           elseif (sssdif .lt. 0.0) then
                 sssdif = -sssrmx(i,j)   ! limit relaxation
           else
                 sssdif = -sssrmx(i,j)   ! limit relaxation   **(It should be sssdif=sssrmx(i,j))**
           endif
        endif

In addition, the relevant salinity flux differences are presented in thermf.F90 also:
Line 92-93:                       salflx(i,j) =             sflice(i,j) +  & !ocn/ice frac. in coupler
                                                                        sssflx(i,j)   !relax  evrywhere
But in the develop branch of hycom2.2.98, at Line 73-90:
if (sss_underice==.false.) then
                 if (covice(i,j)>=0.15) then
                    sssflx(i,j)=0.0                            !skip relaxation bellow sea ice
                 else
                    sssflx(i,j)=(1.0-covice(i,j))*sssflx(i,j)  !skip relaxation bellow sea ice
                 endif
              endif
if     (rivers(i,j,1).eq.0.0) then  !usual case
                 salflx(i,j) =
     &                      (1.0-covice(i,j))*salflx(i,j) +
     &                                        sflice(i,j) + !cell average
     &                                        rivflx(i,j) + !rivers everywhere
     &                                        sssflx(i,j)   !relax everywhere 
              else !a river point
                 salflx(i,j) =                 salflx(i,j) + !might be a river
     &                                        sflice(i,j) + !cell average
     &                                        rivflx(i,j) + !rivers evrywhere
     &                                        sssflx(i,j)   !relax evrywhere
              endif !rivers

So, should these differences be implemented in HYCOM2.3 or during the later development upgrade? Let us discuss this at the group meeting.

**Comment by TillRasmussen** [comment]
I fixed the bug and rewrote the NERSC_HYCOM_CICE part to a more compact version without if statements. It should be the same but that should be tested.

**Pull request merged**
